### ISSUE TITLE
Support for multiple virtual networks

### ISSUE THREAD

**Issue by martinhausio** [Boostport/setup-cloudflare-warp#102]
Hi, we have multiple virtual networks in our setup and would like to be able to choose which one the action will connect to.

the warp-cli supports this by configuring the vnet parameter, passing it the vnet ID prior to connecting

example: 

`warp-cli vnet abcd1234-12ab-34bc-1234-a12344321a`

`warp-cli connect`

**Comment by F21** [comment]
Would you be happy to open a PR to implement this?

I think we can add it as a `with` parameter in the action's configuration:
```
uses: Boostport/setup-cloudflare-warp@v1
with:
  organization: your-organization
  auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
  auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}
  vnet: ${{ secrets.CLOUDFLARE_VNET }}
```
