### ISSUE TITLE
Version '2023.1.133*' for 'cloudflare-warp' was not found

### ISSUE THREAD

**Issue by Flynsarmy** [Boostport/setup-cloudflare-warp#151]
When setting a specific version of cloudflare warp to use (straight out of your docs) like so:
```yaml
- name: Connect to CloudFlare Warp
  uses: Boostport/setup-cloudflare-warp@v1.10.0
  with:
    version: 2023.1.133
    organization: my-org
    auth_client_id: my-clientid
    auth_client_secret: my-clientsecret
```
I get the following error:

> /usr/bin/sudo apt install -y cloudflare-warp=2023.1.133*
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
Reading state information...
Package cloudflare-warp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Version '2023.1.133*' for 'cloudflare-warp' was not found
Error: The process '/usr/bin/sudo' failed with exit code 100

I also tried `2025.1.186.0` which is the latest version. Perhaps your readme could use an update?
