### ISSUE TITLE
Error: WARP is not registered

### ISSUE THREAD

**Issue by Flynsarmy** [Boostport/setup-cloudflare-warp#152]
When not specifying a version:

```yaml
- name: Connect to CloudFlare Warp
  uses: Boostport/setup-cloudflare-warp@v1.10.0
  with:
    organization: my-org
    auth_client_id: my-clientid
    auth_client_secret: my-clientsecret
```

Version `2025.1.861.0` is correctly installed however the runner tries to call
> /usr/bin/warp-cli --accept-tos settings
Merged configuration:
(derived)	Always On: false
(default)	Switch Locked: false
(default)	Mode: Warp
(not set)	WARP tunnel protocol: WireGuard
(local policy)	Disabled for Wifi: false
(local policy)	Disabled for Ethernet: false
(not set)	Resolve via: cloudflare-dns.com @ [162.159.36.1, 162.159.46.1, 2606:4700:4700::1111, 2606:4700:4700::1001]
(not set)	qlog log until: FutureSystemTime(None)
(default)	Onboarding: true
(api defaults)	Exclude mode, with hosts/ips:
...

This repeats about 5 times before eventually ending up at:

> Error: WARP is not registered

Running on ubuntu-latest
