### ISSUE TITLE
WARP is not registered even after following the steps

### ISSUE THREAD

**Issue by mohamedfarees** [Boostport/setup-cloudflare-warp#158]
I am unable to connect my github action with cloudflare warp, In Tunnel i have a VM with private IP which i need to connect using cloudflare.

I have followed the steps and created service auth token, (Access token with no expiry)
In Settings-> Warp client -> Device enrollment permissions created policy and included Service Token
Selctor: Any Access Service token and value as any non expired service token
and access -> policies added a policy for the same
Also unable to perform the activity mentioned in the readme screenshot

Getting below error
(local policy)	Daemon Teams Auth: true
(default)	Disable Auto Fallback: false
(local policy)	Organization: $cloudflare_organization
(local policy)	Auth Client ID: $CLOUDFLARE_AUTH_CLIENT_ID
(not set)	Allow Updates: true
(local policy)	Allowed to Leave Org: false
(local policy)	MDM Configuration: <single-config>
(not set)	Registration Scope: System
Error: WARP is not registered

My action steps
```yml
      - name: Cloudflare warp client Boostport
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: $CLOUDFLARE_ORGANIZATION
          auth_client_id: $CLOUDFLARE_AUTH_CLIENT_ID
          auth_client_secret: $CLOUDFLARE_AUTH_CLIENT_SECRET
```
Note in env added all the secrets and even for service token ther eis no expiry
let me know if you need any ore info
